#!/bin/bash

# A script to perform incremental backups using rsync
# Usage:
#	argos-backup <directory_to_backup>
# Based on: https://linuxconfig.org/how-to-create-incremental-backups-using-rsync-on-linux

set -o errexit
set -o nounset
set -o pipefail

# Configure source and backup dir
# export ARGOS_BACKUP_DIR="${HOME}/git/argos-backup"

readonly SOURCE_DIR=$1
readonly BACKUP_DIR="$ARGOS_BACKUP_DIR/backup/$SOURCE_DIR"

readonly DATETIME="$(date +%s)"
readonly BACKUP_PATH="${BACKUP_DIR}/${DATETIME}"
readonly LATEST_LINK="${BACKUP_DIR}/latest"

mkdir -p "${BACKUP_DIR}"

rsync -av --delete \
  "${SOURCE_DIR}/" \
  --link-dest "${LATEST_LINK}" \
  "${BACKUP_PATH}"

rm -rf "${LATEST_LINK}"
ln -s "${BACKUP_PATH}" "${LATEST_LINK}"

