#!/bin/bash

# https://github.com/josegonzalez/python-github-backup
# pip install github-backup
# export GITHUB_ACCESS_TOKEN=SOME-GITHUB-TOKEN

github-backup argosopentech --token $GITHUB_ACCESS_TOKEN --output-directory ~/git/GitHub/ --repositories
